/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "ROUTES" CASCADE;

CREATE TABLE "ROUTES" (
  "ID" BIGSERIAL NOT NULL PRIMARY KEY,
  "NAME" VARCHAR(50) NULL);

